### ISSUE TITLE
[Info] Jenkins + Maven repo!

### ISSUE THREAD

**Issue by sgdc3** [ChanceSD/AncientGates#10]
With the recent pom changes it works!
Jenkins: http://ci.xephi.fr/job/AncientGates/
Maven repo: http://ci.xephi.fr/plugin/repository/everything/
;)

**Comment by sgdc3** [comment]
@NoChanceSD

**Comment by ChanceSD** [comment]
Nice, if you have a webhook i can add it so it builds automatically on push.

**Comment by sgdc3** [comment]
It should already work, jenkins has a native github hook ;)

**Comment by ChanceSD** [comment]
I don't think so, otherwise anyone would have permission to do this...

**Comment by sgdc3** [comment]
There is only one way to find out: just push some changes ;)

**Comment by sgdc3** [comment]
Ok i found how the github hook works. If you put an oauth code the hook is automatically enabled both side. I don't have access to your repo, so my oauth token is invalid. If you want to enable a webhook you need to add this url to the prebuilt jenkins hook on your project configuration: http://ci.xephi.fr/github-webhook/

**Comment by sgdc3** [comment]
@NoChanceSD

**Comment by ChanceSD** [comment]
Nop, doesn't seem to be working

**Comment by sgdc3** [comment]
Retry now, sorry i forgot to check an option ;)

**Comment by ChanceSD** [comment]
Cool, it worked now =P

**Comment by sgdc3** [comment]
Yeah! ;)
