### ISSUE TITLE
Inventory transfer not working with bungeecord.

### ISSUE THREAD

**Issue by Kuinox** [ChanceSD/AncientGates#17]
Hi !
The inventory transfer do not work.
When i do "/gate setinv portal true" it will use the inventory of the actual server, there is no inventory transfert.
I'm using Ancient gates with sockets to link Bungeecord's servers.

**Comment by ChanceSD** [comment]
That command only works for inventories between worlds afaik, between servers would take quite a bit more work and it's not a feature.

**Comment by Kuinox** [comment]
This worked some hours, then it stopped to work at all.
The entity get their items transfered, it judt dont work witb player.
https://dev.bukkit.org/bukkit-plugins/ancient-gates-reloaded/pages/bungee-cord-usage/
