### ISSUE TITLE
Possible bug(?

### ISSUE THREAD

**Issue by Ancard** [ChanceSD/AncientGates#21]
I do not know why but I get this error in the survival server, I set it identically in the others but I only get the error in the survival.
The server version is Spigot 1.11.2 last update.
If I disconnect the bungeecord support the error disappears.
![capturaerrorancientgates](https://cloud.githubusercontent.com/assets/24949481/21898974/611c4d1a-d8cd-11e6-838a-75a1d51f2287.PNG)

**Comment by razorrider7** [comment]
uhh... btw, your username is visible in the photo, to the left **** issued server command:
