### ISSUE TITLE
Bugs and Errors

### ISSUE THREAD

**Issue by Cha0sPudd1ng** [ChanceSD/AncientGates#3]
Hi,

The following doesn't works or is faulty.
1. teleportInventoryDefault: Doesn't work.
2. When I ride a mob / vehicle, I will not ported.
3. The Chat get spammed and the Items, Vehicles and mobs are Dulpicated when you/they enter the Portal exact between the blocks.
   Example: When you drop a Item and it's enter the Portal between two blocks it get duplicated by 1.
   When you drop a Item and it's enter the Portal between four blocks it get duplicated by 3.
4. I get randomly the following error when i send mobs:

[15:27:45] [Server thread/WARN]: [AncientGates] Task #6415 for AncientGates v1.9.8 generated an exception
java.lang.IllegalArgumentException: Health must be between 0 and 23.0
    at org.bukkit.craftbukkit.v1_8_R3.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:83) ~[spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at org.mcteam.ancientgates.util.EntityUtil.setEntityTypeData(EntityUtil.java:163) ~[?:?]
    at org.mcteam.ancientgates.util.TeleportUtil.teleportEntity(TeleportUtil.java:271) ~[?:?]
    at org.mcteam.ancientgates.listeners.PluginSocketListener$1.run(PluginSocketListener.java:194) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_05]

**Comment by ChanceSD** [comment]
So number 4 should be fixed. Can you give more details on number 3? 
How do i make an item go between 2 portal blocks?

**Comment by Cha0sPudd1ng** [comment]
Oh Sry, i have see only now your Post.

Here is a Picture, write me if you want more help ;-)

http://img5.fotos-hochladen.net/uploads/agduplicatebugz8rh4t2ukn.png

**Comment by ChanceSD** [comment]
Only works on horizontal portals or vertical too?
Btw, what texture is that? Looks pretty good xD

**Comment by Cha0sPudd1ng** [comment]
I have testet it now, the Bug is only by the horizontal portals, and only by BungeeCord.

Server Intern works good. ;-)

Yeah this Texturepack is a Remake from the Original Minecraft Texturepack.
But it's not finished.

It's the 'Smooth Realism'

Here the Link:

http://www.minecraftforum.net/forums/mapping-and-modding/resource-packs/1241290-r3d-craft-default-realism-smooth-realism-v0-2-2

**Comment by ChanceSD** [comment]
Thanks but so far i couldn't get any duplicated items, also teleport inventory and riding mobs worked fine. Try the latest version and see if it works maybe or give me more details.

**Comment by Cha0sPudd1ng** [comment]
Hmm

I have tested it with the AncientGates version 2.0.3

Here is a video over the Bug: https://www.youtube.com/watch?v=7ZvuyWbqW6M

Here my AncientGates Settings: http://workupload.com/file/f5cmUWcJ

I used following plugins and versions:

Spigot: version git-Spigot-0359393-9cd1111 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
https://www.spigotmc.org/wiki/spigot/

BungeeCord: 1087
https://www.spigotmc.org/wiki/bungeecord/

BungeeTabListPlus:
https://www.spigotmc.org/resources/bungeetablistplus.313/

AncientGates:
https://www.spigotmc.org/resources/ancient-gates.6583/

Dynmap:

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286593-dynmap-dynamic-web-based-maps-for-minecraft

WorldEdit:
http://dev.bukkit.org/bukkit-plugins/worldedit/

WorldBorder:
http://dev.bukkit.org/bukkit-plugins/worldborder/

**Comment by ChanceSD** [comment]
Ok so after a lot of time testing this and debugging my conclusion is that using sockets isn't really a good idea, it's not necessary unless you really want to.

With that said, i think i managed to fix this issue for now, let me know how it worked after i upload the new version at Spigot.

**Comment by Cha0sPudd1ng** [comment]
K THX. :-)

But if the Sockets is not really needed for what it's good?

I thought it would be better if you use it.

**Comment by ChanceSD** [comment]
I'm still not sure as i got this project recently but afaik it is more reliable as the servers communicate with each other. 
However it also has the potential to have other bugs like this one and is a lot more difficult to maintain the code. Basically what i'm saying is to be careful as there might be other dupe bugs yet.

**Comment by Cha0sPudd1ng** [comment]
HEY, THX for Upgrade. :-)

But now i get the error: Still connecting to BungeeCord. Try again. With and without Socket.
- I have following tested with the version 2.0.3 without Socket. 
  If I throw the items into the portal, it is a pure lottery whether they arrive on the other side or not.
- And in the version 2.0.3 the Inventory of the Players, and Player they Riding mobs don't get Portet. With and without Socket.

**Comment by ChanceSD** [comment]
With version 2.0.5 too? Make sure you use same version on all servers.

**Comment by Cha0sPudd1ng** [comment]
By the version 2.0.5 i get the Error: Still connecting to BungeeCord. Try again. With and without Socket.

And when i go into a existing portal i get the Error: Error connecting to Server. Try again.

**Comment by Cha0sPudd1ng** [comment]
Is have it now again with the 2.0.5 version tested and installed me satisfied that on all servers have the same version.

Unfortunately still comes the aforementioned error.

**Comment by ChanceSD** [comment]
Is that the only error? No detailed errors like exceptions?

**Comment by Cha0sPudd1ng** [comment]
Even with the debug mode I get no more detailed error message. SRY

**Comment by Cha0sPudd1ng** [comment]
Hey.

Very nice work. Now it's work with and without Sockets.

I let Sockets now disabled, as it can lead to problems so, as you said.

You have this plugin advanced very far. Many thanks :-)

Can you Fix the Inventory teleport bug? 

I think that has priority. But I want to prescribe you anything. ;-)

**Comment by ChanceSD** [comment]
If you mean teleport inventory through bungee? That probably won't get added, if you don't mean that, i'm not sure what are other issues with inventory.

**Comment by Cha0sPudd1ng** [comment]
We have two servers , they are connected by the plugin . The problem is when you walk, through the portal from one to the other server then currently , each server has its own and not the same inventory.

**Comment by ChanceSD** [comment]
Yes, that's not a feature from this plugin, each server has it's inventory.

**Comment by Cha0sPudd1ng** [comment]
Hey, i have a idea. I have a root and i can Symlink the playerdata between the Servers. But before the Player get Portet, the Playerdata muss saved.

When you can make that the playerdata get saved first before the Player get Portet, the Player have then the same Inventory, Armor, Potions, Effects etc. on the other server. ;-)

**Comment by ChanceSD** [comment]
That actually sounds like it would work xD
I believe the server saves the data as soon as the player leaves, you just have to hope that it saves before the player actually gets to the other server. It might work without me adding anything, let me know if you ever try it.

**Comment by Cha0sPudd1ng** [comment]
Hey, i have try it. But the teleport is to fast. In the Second test i have used the exec feature of your Plugin with the save-all command. But it's also much too fast

I think it's must first complete saved the Playerdata and after that the Teleport.

It works when I use Manuel the Save-all Command and go in the Portal.

**Comment by Cha0sPudd1ng** [comment]
The Itembug returns!

Sometimes the Items, we drop into the Portal, was duplicated and sometimes they just dissappered.

It makes no matter whether socket is set on or off.

Especially when two or more people use different portals at the same time

**Comment by ChanceSD** [comment]
It has been a while but does it happen on bungee portals only?

**Comment by sgdc3** [comment]
Bump!

**Comment by sgdc3** [comment]
Any news about this issue?
