### ISSUE TITLE
Horizontal gates with material "portal" are not end portal material

### ISSUE THREAD

**Issue by c0wg0d** [ChanceSD/AncientGates#33]
**Describe the bug**
/gate setmaterial id portal
In a 3x3 horizontal area like an end portal
Material is nether portal, not end portal

**Expected behavior**
I expect it to look like an end portal

**Plugin and Server version**
2.3
Paper 1.15.2

![2020-05-19_00 36 29](https://user-images.githubusercontent.com/10082424/82298378-e53f4980-9968-11ea-8bd4-e27f15d89cb0.png)

**Comment by c0wg0d** [comment]
I have this same issue.  The plugin is still being actively maintained, but this bug report has been open for over a year.  Can we please get a fix for this?

**Comment by ChanceSD** [comment]
You're probably using an outdated version, I tried 1.17 and 1.15 and it worked just fine. Yes, I should have probably closed the report then.

**Comment by ChanceSD** [comment]
So I'm gonna assume you also got it working :)
