### ISSUE TITLE
bad portal rotation?

### ISSUE THREAD

**Issue by Poweringg** [ChanceSD/AncientGates#42]
**Describe the bug**
Portal is badly rotated in his frame.

**To Reproduce**
1. Build frame 4x3 of any material, with back as on screens...
2. /gate create xxx
3. /gate setfrom xxx
4. /gate open xxx
5. gate is badly rotated

when i closed portal using "/gate close xxx", i got some err in console:
```
[21:32:58 ERROR]: POI data mismatch: never registered at BlockPosition{x=1111, y=4, z=484}
[21:32:58 ERROR]: POI data mismatch: never registered at BlockPosition{x=1111, y=5, z=484}
[21:32:58 ERROR]: POI data mismatch: never registered at BlockPosition{x=1111, y=6, z=484}
[21:32:58 ERROR]: POI data mismatch: never registered at BlockPosition{x=1111, y=7, z=484}
```

**Plugin and Server version**
AGates 2.3
Paper 1.16.1 127

**Screenshots (Optional)**
Frame of the portal.. Gold block is "set from"
![image](https://user-images.githubusercontent.com/15527318/90176908-04a01400-ddaa-11ea-8a84-78bf1d57227a.png)
....
![image](https://user-images.githubusercontent.com/15527318/90176962-1a153e00-ddaa-11ea-943a-e4c9ac6bba88.png)
... but when i remove stone back, it works.
![image](https://user-images.githubusercontent.com/15527318/90177128-5e084300-ddaa-11ea-8275-175285e6da50.png)

**Comment by ChanceSD** [comment]
Seems like since it's such a closed space, the plugin doesn't know if it should go vertical or diagonal orientation. 
Also, probably because it sees the trapdoors as full blocks so that also interferes, I will need to recreate this portal to know for sure though.

**Comment by Poweringg** [comment]
Update with better portal screens, hope it helps.. When build "corridor" (no matter how long) with same size of portal, portal wont open normally. But when i remove "corridor" portal is ok after "/gate open..."

**With corridor:**
![image](https://user-images.githubusercontent.com/15527318/90343272-3cf45c00-e00f-11ea-82aa-48ca8fe75988.png)
![image](https://user-images.githubusercontent.com/15527318/90343286-644b2900-e00f-11ea-842c-944bc8b951c0.png)
![image](https://user-images.githubusercontent.com/15527318/90343294-7927bc80-e00f-11ea-85a5-b092cde3ff15.png)


**There's corridor removed:**
![image](https://user-images.githubusercontent.com/15527318/90343322-b55b1d00-e00f-11ea-829c-92feb68825e6.png)

**Or only back removed:**
![image](https://user-images.githubusercontent.com/15527318/90343334-d6bc0900-e00f-11ea-960f-b7fc6bfd6876.png)

**Or part of corridor removed:**
![image](https://user-images.githubusercontent.com/15527318/90343352-f5220480-e00f-11ea-95ad-2fefeb4d96d3.png)

**And it also works, when i remove only this one gold block:**
When i try to remove any other one block, it again not works. It works only without this one block.
![image](https://user-images.githubusercontent.com/15527318/90343400-534ee780-e010-11ea-937d-e30430024795.png)
.... my try to remove any other block ....
![image](https://user-images.githubusercontent.com/15527318/90343432-a9bc2600-e010-11ea-9201-4e814ab528c4.png)
... but this works ...
![image](https://user-images.githubusercontent.com/15527318/90343485-ff90ce00-e010-11ea-9462-845f6f71caca.png)

**Comment by Poweringg** [comment]
there not working even previous method with corridor removal.. gold block is "setFrom"
![image](https://user-images.githubusercontent.com/15527318/90343668-015b9100-e013-11ea-9bb9-975494065716.png)

but there it works, i dont know.. too much drugs for today.. 😃 
![image](https://user-images.githubusercontent.com/15527318/90343784-f81ef400-e013-11ea-8f68-49c375d8d1e1.png)

**Comment by ChanceSD** [comment]
I know it has been a long time but this happened because the plugin assumed you wanted a diagonal portal since it would be smaller than a regular vertical portal. I added a config option that disabled diagonal portals by default as most people won't want them anyway.
