### ISSUE TITLE
Sponge

### ISSUE THREAD

**Issue by ChanceSD** [ChanceSD/AncientGates#5]
Maybe add Sponge compatiblity

**Comment by wi-ta** [comment]
I love to see this Plugin on Forge/Sponge

**Comment by ChanceSD** [comment]
I haven't been keeping up with Sponge development though but maybe some day.

**Comment by wi-ta** [comment]
Well then have a look they do a plugin contest now.
https://www.spongepowered.org/

**Comment by sgdc3** [comment]
-1 I hate sponge xD
