### ISSUE TITLE
End Gateway Material

### ISSUE THREAD

**Issue by nutellarlz** [ChanceSD/AncientGates#65]
**Is your feature request related to a problem? Please describe.**
Sort of...  If I use the "portal" material for a horizontal gate I get the end portal, but vertical gates use the nether portal.  This is good.  I just wish I could have the end portal texture but vertical.

**Describe the solution you'd like**
To achieve this, a new material could be added using the End Gateway.  This block looks like the end portal, just flipped on its side, thus solving the problem.

**Comment by ChanceSD** [comment]
This would be cool but I'm not sure if it would be possible to do. Never tried it but I think the end gateway doesn't fill a whole block so it would look like portal bars if it's even possible to have multiple of them side by side without them breaking. I will get it a try when I can though.

**Comment by nutellarlz** [comment]
I'm not sure if it helps, it probably doesn't, but I've attached a screenshot of a redesigned end portal room from a server I admin.  It uses end gateways to make a vertical portal somewhat reminiscent of a nether portal.  Granted, there is a 3x1 end portal under the gateway blocks because the gateway blocks have no native functionality in the overworld.

![2021-03-02_20 04 01](https://user-images.githubusercontent.com/11525549/123031889-edeb2600-d399-11eb-89e9-b46ab13cf1b7.png)

**Comment by ChanceSD** [comment]
Took a bit of work but it seems to work just fine, try this when you can: https://ci.codemc.io/job/ChanceSD/job/AncientGates/25/
You can set any portal to use end gateways with /gate setmaterial id ENDGATEWAY
I will probably upload it to Spigot soon if there are no issues.
