### ISSUE TITLE
Vehicle Teleportation

### ISSUE THREAD

**Issue by AliensHive** [ChanceSD/AncientGates#7]
We switched vehicle.teleportation to "true" in the settings.

Everytime we send a minecart through a portal, it will get teleported to the
"setto"-position, but always a little bit higher. 
The issue after the 10th minecart or so is, that it'll jump from above 3 blocks or higher towards the rails on the other side.
I'll guess that the "setto"-position moves slightly higher and higher in altitude with every vehicle that moves through portals. Even players walking through that portal will end up teleported into the air.

We use AncientGates for our railroad-system on our server.

**Comment by AliensHive** [comment]
My opinion is, that 
teleportutil.class add 0.5 height to a vehicle for teleporting safely,
the destination-point get's changed, but its height is not corrected afterwards by -0,5

**Comment by sgdc3** [comment]
Can you upload an explaining video? ;)

**Comment by AliensHive** [comment]
just send 20 Minecarts through a portal and walk through it after them.
You'll see that you got teleported not to the setto-position, but a few blocks higher.

Or you can make a portal and set the "setto-pos" behind it.
Now build a ring of rails from the "setto-position" around and back to the "setfrom-pos".
Set a furnace minecart on the rails, power it, and wait.
You'll see that it begins to hover higher and higher with every teleport.

**Comment by freew67** [comment]
Here is the error AliensHive is talking about.  We are getting the exact same error.

https://www.youtube.com/watch?v=IBWoxuWRcLQ

**Comment by sgdc3** [comment]
wtf? xD

**Comment by ChanceSD** [comment]
lol What black magic is this?!

**Comment by freew67** [comment]
Does the same thing for boats as well.

**Comment by AliensHive** [comment]
Look at **TeleportUtil.java** (line 295):
Code adds 0.5 to destination height.

This should be corrected after successful teleport, like adding:
final Location destination = GeometryUtil.addHeightToLocation(location, -0.5);
